WebPapi/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as users_views
urlpatterns = [
    path('', include('papi.urls')),
    path('bem/', include('bempapi.urls')),
    path('dosen/', include('dosenpapi.urls')),
    path('admin/', admin.site.urls),
    # Perlu diubah untuk Login sesuai projek lost found
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html') ,name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='papi/index.html') ,name='logout'),
    path('register/',users_views.register,name='register'),
    path('register-dosen/',users_views.register_dosen,name='register-dosen'),
    path('profile-mahasiswa/', users_views.profie_mahasiswa, name='profile-mahasiswa')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

papi/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('upload-page/', views.upload_pkm, name='upload-page'),
    path('multiple-input/', views.coba_multiple_input, name='multiple-input'),
    path('input-anggota/', views.input_anggota, name='input-anggota'),
    path('proposal-pkm/<idPkm>/', views.proposal_pkm_page, name='proposal-pkm'),
    path('download-format/', views.download_format_pkm, name='format-pkm'),
    path('info-dosen/', views.info_dosen, name='info-dosen'),
    path('log-file/', views.log_file, name='log-file'),
    path('list-format', views.list_format, name='list-format'),
    path('dashboard-mhs', views.dashboard_mhs, name='dashboard-mhs'),
    path('input-dospem', views.input_dospem, name='input-dospem'),
    path('timeline-mahasiswa', views.timeline_mahasiswa, name='timeline-mahasiswa'),
    path('download_revisi/<path>/',
         views.download_revisi, name='download-revisi'),
    path('update/<idUsers>', views.update_pkm, name='update-pkm'),
    path('list_anggota/<idUser>', views.list_anggota, name='list-anggota'),
    path('view_dosbim/<idUser>', views.view_dosbim, name='view-dosbim'),
    path('update_anggota/<idAnggota>/',
         views.update_anggota, name='update-anggota'),
    path('update_dosbim/<idDosbim>/',
         views.update_dosbim, name='update-dosbim'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.utils.translation import ugettext_lazy as _

from .managers import CustomUserManager


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    kontak = models.CharField(max_length=13)
    username = None
    email = models.EmailField(unique=True, null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return f'{self.pk, self.email}'


class Mahasiswa(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    npm = models.IntegerField(blank=True, null=True)
    fakultas = models.ForeignKey(
        'Fakultas', on_delete=models.CASCADE, default=1)
    jurusan = models.ForeignKey('Jurusan', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f'{self.user}'


class Dosen(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    nip = models.IntegerField(blank=True, null=True)
    bidang = models.ForeignKey(
        'papi.KategoriPKM', on_delete=models.CASCADE, default=1)
    fakultas = models.ForeignKey(
        'Fakultas', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f'{self.user}'


class Fakultas(models.Model):
    namaFakultas = models.CharField(max_length=10, default="")

    def __str__(self):
        return f'{self.namaFakultas}'


class Jurusan(models.Model):
    namaJurusan = models.CharField(max_length=100, default="")
    idFakultas = models.ForeignKey(
        "Fakultas", on_delete=models.CASCADE, default=0)

    def __str__(self):
        return f'{self.namaJurusan}'

users/forms.py
from django import forms
# from .models import Registration
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Mahasiswa, Dosen

User = get_user_model()


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()
    is_student = forms.BooleanField(initial=False, required=False)
    is_teacher = forms.BooleanField(initial=False, required=False)
    # npm = forms.IntegerField()
    # fakultas = forms.IntegerField()
    # jurusan = forms.IntegerField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'kontak', 'email',
                  'password1', 'password2', 'is_student', 'is_teacher', 'kontak')
    #    fields=('username','email','password1','password2','is_student','is_teacher','npm','fakultas','jurusan')
    # def save(self,commit = True):
    #     user = super(RegistrationForm,self).save(commit = False)
    #     user.email = self.cleaned_data['email']
    #     user.mahasiswa.npm = self.cleaned_data['npm']
    #     user.mahasiswa.fakultas = self.cleaned_data['npm']
    #     user.mahasiswa.jurusan = self.cleaned_data['npm']

    #     if commit:
    #         user.save()


class MahasiswaRegisForm(forms.ModelForm):
    class Meta:
        model = Mahasiswa
        fields = ('npm', 'fakultas', 'jurusan')


class DosenRegisForm(forms.ModelForm):
    class Meta:
        model = Dosen
        fields = ('nip', 'bidang', 'fakultas')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import RegistrationForm, MahasiswaRegisForm, DosenRegisForm
from django.contrib import messages
from .models import Fakultas, Jurusan, Mahasiswa
from papi.models import KategoriPKM
from django.contrib.auth import get_user_model
User = get_user_model()
# Create your views here.
# For Student


def register(request):
    fakultas = Fakultas.objects.all()
    jurusan = Jurusan.objects.all()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        m_form = MahasiswaRegisForm(request.POST)
        if form.is_valid() and m_form.is_valid():
            user = form.save()
            email = form.cleaned_data.get('email')
            user.refresh_from_db()
            user.email = email
            try:
                user.mahasiswa.npm = m_form.cleaned_data.get('npm')
                user.mahasiswa.fakultas = m_form.cleaned_data.get('fakultas')
                user.mahasiswa.jurusan = m_form.cleaned_data.get('jurusan')
            except Mahasiswa.DoesNotExist:
                messages.success(
                    request, f'You Haven\'t agree with the terms!')
                return redirect('register')
            user.save()

            # form_user = form.save(commit=False)
            # form_user.is_student = True
            # form_user.save()
            # form = self.form_class( request.POST)
            # if form.is_valid():
            # new_formfile = form.save(commit=False)
            # new_formfile.is_activate = true
            # new_formfile.save()
            messages.success(request, f'Account created for {email}!')
            return redirect('index')
        else:
            print("Error di form")
    else:
        form = RegistrationForm()
        m_form = MahasiswaRegisForm()
    context = {
        'form': form,
        'm_form': m_form,
        'jurusan': jurusan,
        'fakultas': fakultas,
    }
    return render(request, 'users/register.html', context)


def register_dosen(request):
    fakultas = Fakultas.objects.all()
    bidang = KategoriPKM.objects.all()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        m_form = DosenRegisForm(request.POST)
        if form.is_valid() and m_form.is_valid():
            user = form.save()
            email = form.cleaned_data.get('email')
            user.refresh_from_db()
            user.email = email
            user.dosen.nip = m_form.cleaned_data.get('nip')
            user.dosen.bidang = m_form.cleaned_data.get('bidang')
            user.dosen.fakultas = m_form.cleaned_data.get('fakultas')
            user.save()
            messages.success(request, f'Account created for {email}!')
            return redirect('index')
        else:
            print("Error di form")
    else:
        form = RegistrationForm()
        m_form = DosenRegisForm()
    context = {
        'form': form,
        'm_form': m_form,
        'fakultass': fakultas,
        'bidangs': bidang,
    }
    return render(request, 'users/registerdosen.html', context)


def profie_mahasiswa(request):
    return render(request, 'users/profil.html')

users/templates/users/login.html
{% extends 'papi/base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>WebPapi</title>
    <link rel="stylesheet" href="{% static 'papi/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'papi/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'papi/css/Login-Form-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'papi/css/Registration-Form-with-Photo.css' %}">
    <link rel="stylesheet" href="{% static 'papi/css/styles.css' %}">
    <link rel="icon" href="{% static 'papi/img/Logo.png' %}">
</head>
<body>

{% block content %}
    <div class="login-clean" style="background-color: #FAF1E8;">
        <form class="border rounded" action="{% url 'login' %}" method="POST" style="min-width: 60%;margin-top: -50px;margin-bottom: 50px;margin-top: 50px; box-shadow: 0 6px 20px 0 rgba(0, 0, 0, 0.15), 0 6px 20px 0 rgba(0, 0, 0, 0.15); margin-right: 10%; margin-left: 18%;background-color: #fbead8;">
            {% csrf_token %}
            <h2 class="sr-only">Login Form</h2>
            <div class="illustration">
                <div><img src="{% static 'papi/img/Login.jpg' %}" class="center"></div>
            </div>
{#                    <div class="form-group"><input class="form-control" type="email" name="username" id="email" placeholder="Email" style="background-color: #e5e5e5;"></div>#}
{#        <div class="form-group"><input class="form-control" type="password" name="password" id="password" placeholder="Password" style="background-color: #e5e5e5;"></div>#}
            <div class="form-group"><input class="form-control" type="email" name="username" placeholder="Email" style="background-color: #e5e5e5;"></div>
            <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Password" style="background-color: #e5e5e5;"></div>
            <div class="form-group"><button class="btn btn-primary btn-block" type="submit" style="background-color: #ffa883;">Log In</button></div>
            <div class="form-row justify-content-center">
                <div class="col-4 text-center">
                    <p class="text-center" style="font-size: 20px;">Belum Ada Akun?</p>
                </div>
                <div class="col-2"><a href="{% url 'register' %}" class="forgot" style="color: #FFA883;font-size: 20px;">Register</a></div>
            </div>
        </form>
    </div>

{% endblock %}
<script src="{% static 'papi/js/jquery.min.js' %}"></script>
<script src="{% static 'papi/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

users/templates/users/profil.html
{% extends 'papi/base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>WebPapi</title>
    <link rel="stylesheet" href="{% static 'papi/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'papi/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'papi/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'papi/fonts/ionicons.min.css'%}">
    <link rel="stylesheet" href="{% static 'papi/css/Login-Form-Clean.css' %}">
</head>
<body>
    {% block content %}
    <div class="container-fluid text-center" style="background-image: url({% static 'papi/img/Head.jpg' %});background-position: top;background-size: auto;">
        <div style="min-height: 330px;"></div>
    </div>
    <div class="login-clean" style="background-color: #FAF1E8;">
        <div class="container" style="min-width: 80%;background-color: #fbead8;margin-top: -50px;margin-bottom: 50px; box-shadow: 0 6px 20px 0 rgba(0, 0, 0, 0.15), 0 6px 20px 0 rgba(0, 0, 0, 0.15); margin-right: 10%; margin-left: 7%">
            <div class="form-row">
                <div class="col">
                    <p class="text-center" style="color: #70c7e2;font-size: 30px;font-weight: bold;">Profile Mahasiswa<br></p>
                                <div class="illustration">
                    <div><img src="{% static 'papi/img/Logo.png' %}" class="center" style="width:300px;height:300px;"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <p class="text-center" style="color: #FFA883;font-size: 30px;font-weight: bold;">Nama Mahasiswa<br></p>
                    <p class="text-center" style="color: #FFA883;font-size: 30px;font-weight: bold;">NPM Mahasiswa<br></p>
            <div class="row">
                <div class="col">
                    <p class="text" style="color: #FFA883;font-size: 20px;margin-right: 10%;margin-left: 10%"><br>About Me:<br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent laoreet commodo augue, quis vestibulum lectus rhoncus vel. Aliquam blandit augue vitae arcu volutpat maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam id felis eget sem porttitor consectetur nec ac turpis. Phasellus ut mauris est. Quisque a gravida ipsum. Quisque tempus lorem quis nisi posuere suscipit. Ut eget est eu metus elementum rutrum eget quis tellus. Duis a purus leo. Suspendisse ullamcorper bibendum tellus, mollis fermentum diam rutrum id. Nullam ut tortor sit amet urna elementum tristique eget ac lacus. Integer vel erat magna. Sed vitae odio porttitor, volutpat arcu non, malesuada est. Fusce dictum tellus in posuere venenatis. Maecenas malesuada velit at est elementum maximus. Etiam placerat augue ac ex vulputate vehicula.<br><br>In felis nisl, sodales ut molestie nec, porttitor quis libero. In interdum ultrices faucibus. Sed vitae felis dictum, porttitor ante consectetur, luctus sem. Sed facilisis dapibus est a elementum. Mauris eleifend nibh ac cursus lacinia. Morbi risus massa, fringilla placerat tortor sit amet, rhoncus sagittis ipsum. Cras venenatis arcu quis augue accumsan imperdiet. Etiam faucibus, diam eget sollicitudin venenatis, velit lorem aliquam metus, nec scelerisque ex odio sit amet sem.<br></p></div>
            </div>
        </div>
    </div>
    </div>
    </div>
    {% endblock %}

</body>
</html>

users/templates/users/registerdosen.html
{% extends 'papi/base.html' %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>WebPapi</title>
    <link rel="stylesheet" href="{% static 'papi/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'papi/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'papi/css/Login-Form-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'papi/css/Registration-Form-with-Photo.css' %}">
    <link rel="stylesheet" href="{% static 'papi/css/styles.css' %}">
    <link rel="icon" href="{% static 'papi/img/Logo.png' %}">
</head>

<body>
    {% block content %}

    <div class="register-photo" style="background-color: #FAF1E8;">
        <div class="login-clean" style="background-color: #FAF1E8;">
            <div class="form-container" style="background-color: #FDE3C8;">
                <form method="POST" action="{% url 'register-dosen' %}" enctype="multipart/form-data"
                    class="border rounded"
                    style="min-width: 60%;background-color: #fbead8;margin-top: -50px;margin-bottom: 50px;margin-top: 50px; box-shadow: 0 6px 20px 0 rgba(0, 0, 0, 0.15), 0 6px 20px 0 rgba(0, 0, 0, 0.15); margin-right: 10%; margin-left: 18%">
                    {% csrf_token %}
                    <div class="illustration">
                        <div><img src="{% static 'papi/img/Login.jpg' %}" class="center"></div>
                    </div>
                    <!-- <div class="form-group"><input class="form-control" type="text" name="username"
                            placeholder="Username" style="background-color: #f0f9fc;"></div> -->
                    <div class="form-group"><input class="form-control" type="text" name="first_name"
                            placeholder="First Name" style="background-color: #f0f9fc;"></div>
                    <div class="form-group"><input class="form-control" type="text" name="last_name"
                            placeholder="Last Name" style="background-color: #f0f9fc;"></div>
                    <div class="form-group"><input class="form-control" type="number" name="nip" placeholder="NIP"
                            style="background-color: #f0f9fc;"></div>
                    <div class="form-group"><label class="text-center" style="font-weight: normal;">Fakultas</label>
                        <select class="form-control" name="fakultas" style="background-color: #f0f9fc;">
                            <optgroup label="Fakultas">
                                {% for fakultas in fakultass %}
                                <option value="{{ fakultas.pk }}" selected="">{{ fakultas.namaFakultas }}</option>
                                {% endfor %}
                            </optgroup>
                        </select>
                    </div>

                    <div class="form-group"><label class="text-center" style="font-weight: normal;">Bidang</label>
                        <select class="form-control" name="bidang" style="background-color: #f0f9fc;">
                            <optgroup label="Bidang">
                                {% for bidang in bidangs %}
                                <option value="{{ bidang.pk }}">{{ bidang.namaKategori }}</option>
                                {% endfor %}
                            </optgroup>
                        </select>
                    </div>
                    <div class="form-group"><input class="form-control" type="number" name="kontak" placeholder="No HP"
                            style="background-color: #f0f9fc;"></div>
                    <div class="form-group"><input class="form-control" type="email" name="email" placeholder="Email"
                            style="background-color: #f0f9fc;"></div>
                    <div class="form-group"><input class="form-control" type="password" name="password1"
                            placeholder="Password" style="background-color: #f0f9fc;"></div>
                    <div class="form-group"><input class="form-control" type="password" name="password2"
                            placeholder="Password (repeat)" style="background-color: #f0f9fc;"></div>
                    <div class="checkbox-row">
                        <input type="checkbox" name="is_teacher" id="id_is_teacher" checked="checked" style="opacity:0;"
                            value="True">
                    </div>
                    {#                {{form.as_p}}#}
                    {#                {{m_form.as_p}}#}
                    <div class="form-group"><button class="btn btn-primary btn-block" type="submit"
                            style="background-color: #FFA883;color: #FAF2E8;">Daftarkan</button></div>

                    {% if m_form.errors %}
                    <p>{{ m_form.errors }} Hai</p>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

    <script src="{% static 'papi/js/jquery.min.js' %}"></script>
    <script src="{% static 'papi/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

users/templates/users/registerdosen_old.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>WebPapi</title>
    <link rel="stylesheet" href="{% static 'papi/css/Registration-Form-with-Photo.css' %}">
    <link rel="stylesheet" href="{% static 'papi/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'papi/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'papi/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'papi/fonts/ionicons.min.css'%}">
    <link rel="stylesheet" href="{% static 'papi/css/Login-Form-Clean.css' %}">
</head>

<body style="background-color: #FAF2F8;">
<div class="container-fluid text-center d-inline-block" style="background-image: url(&quot;{% static 'papi/img/Header.png'%}&quot;);background-position: 100% 50%;background-size: contain;background-repeat: round;min-height: 110px;margin-top: 0px;padding: 0px;">
    <div class="row text-center justify-content-center align-items-center align-content-center mx-auto" style="margin-top: 20px;background-position: center;background-size: contain;background-repeat: repeat;">
        <div class="col text-center"><a class="btn btn-custom btn-lg" type="button" style="width: 200px; text-decoration: none;" role="button" href="{% url 'index' %}">Informasi PKM</a></div>
        <div class="col text-center"><a class="btn btn-custom btn-lg" type="button" style="width: 200px; text-decoration: none;" role="button" href="{% url 'login' %}">Informasi Dosen</a></div>
        <div class="col text-center"><a class="btn btn-custom btn-lg" type="button" style="width: 200px; text-decoration: none;" role="button" href="{% url 'login' %}">Timeline</a></div>
        <div class="col text-center"><a class="btn btn-custom btn-lg" type="button" style="width: 200px; text-decoration: none;" role="button" href="{% url 'login' %}">Format</a></div>
        {% if user.is_authenticated %}
            <div class="col text-center"><a class="btn btn-custom btn-lg" type="button" style="width: 200px; text-decoration: none;" role="button" href="{% url 'login' %}">Profile</a></div>
        {% else %}
            <div class="col text-center"><a class="btn btn-custom btn-lg" type="button" style="width: 200px; text-decoration: none;" role="button" href="{% url 'login' %}">Login</a></div>
        {% endif %}
    </div>
</div>

<div class="register-photo" style="background-color: #FFFFFF;">
    <div class="form-container" style="background-color: #FDE3C8;">
        <form method="POST" style="background-color: #FDE3C8;" action="{% url 'register-dosen' %}" >
            {% csrf_token %}
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            {% if m_form.errors %}
                {% for field in m_form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in m_form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="form-group"><input class="form-control" type="text" name="username" placeholder="Username" style="background-color: #E5E5E5;"></div>
            <div class="form-group"><input class="form-control" type="text" name="first_name" placeholder="First Name" style="background-color: #E5E5E5;"></div>
            <div class="form-group"><input class="form-control" type="text" name="last_name" placeholder="Last Name" style="background-color: #E5E5E5;"></div>
            <div class="form-group"><input class="form-control" type="email" id="email" name="email" placeholder="Email" style="background-color: #E5E5E5;"></div>
            <div class="form-group"><input class="form-control" type="password" id="password1" name="password1" placeholder="Password" style="background-color: #E5E5E5;"></div>
            <div class="form-group"><input class="form-control" type="password" id="password2" name="password2" placeholder="Password (repeat)" style="background-color: #E5E5E5;"></div>
            <div class="form-group"><input class="form-control" type="number" name="kontak" placeholder="No HP" style="background-color: #E5E5E5;"></div>
            <div class="form-group"><input class="form-control" type="number" name="nip" placeholder="NIP"  style="background-color: #E5E5E5;"></div>
            <div class="form-group"><label class="text-center" style="font-weight: normal;">Bidang</label>
                <select class="form-control" name="bidang" style="background-color: #E5E5E5;">
                    <optgroup label="Bidang">
                        {% for bidang in bidangs %}
                            <option value="{{ bidang.pk }}">{{ bidang.namaBidang }}</option>
                        {% endfor %}

                    </optgroup>
                </select>
            </div>
            <div class="form-group"><label class="text-center" style="font-weight: normal;">Fakultas</label>
                <select class="form-control" name="bidang" style="background-color: #E5E5E5;">
                    <optgroup label="Bidang">
                        {% for fakultas in fakultass %}
                            <option value="{{ fakultas.pk }}" selected="">{{ fakultas.namaFakultas }}</option>
                        {% endfor %}

                    </optgroup>
                </select>
            </div>
            <div class="checkbox-row">
                <input type="checkbox" name="is_teacher" id="id_is_teacher" checked="checked" style="opacity:0;" value="True">
            </div>
            <!-- {{form.as_p}}
                {{m_form.as_p}} -->
            <div class="form-group"><button class="btn btn-primary btn-block" type="submit" style="background-color: #ffa883;">Register</button></div>
        </form>
    </div>
</div>


<script src="assets/js/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>